version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: filesize
    versions:
    - 6.1.0
    - 6.2.1
    - 6.2.2
    - 6.2.5
    - 6.2.6
  - dependency-name: grunt-cli
    versions:
    - 1.3.2
    - 1.4.1
  - dependency-name: grunt-contrib-nodeunit
    versions:
    - 2.1.0
